# Generated by Django 6.0.2 on 2026-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Przepis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('skladniki', models.TextField()),
                ('opis', models.TextField()),
                ('czas', models.CharField(blank=True, max_length=100)),
                ('tagi', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
