# Generated by Django 6.0.2 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("przepisy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("user_text", models.TextField(blank=True)),
                ("option1_title", models.CharField(blank=True, max_length=255)),
                ("option1_recipe_id", models.IntegerField(blank=True, null=True)),
                ("option2_title", models.CharField(blank=True, max_length=255)),
                ("option2_recipe_id", models.IntegerField(blank=True, null=True)),
                ("action", models.CharField(max_length=20)),
                ("chosen_index", models.IntegerField(blank=True, null=True)),
                ("follow_up_answer", models.TextField(blank=True)),
            ],
        ),
    ]
